# USED FOR LOCAL DEVELOPMENT ONLY.
# SEE: https://github.com/BretFisher/node-docker-good-defaults
# SEE: https://github.com/kyhsa93/nestjs-rest-cqrs-example
# SEE: https://github.com/ArturKisov/nestjs-mysql-starter

version: '3.9'

services:
  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - redis
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS:
        dump-alter dump-date dump-json edit-foreign email-table enum-option
        enum-types file-upload foreign-system table-indexes-structure
        table-structure tables-filter
    links:
      - redis:${REDIS_HOST}
    ports:
      - ${ADMINER_PORT}:8080
    privileged: true
    restart: always
    volumes:
      - ./db/data:/db/data
      - ./db/public/plugins-enabled/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
  app:
    container_name: app
    # NOTE: Used to enhance DX ONLY. Production image is prefixed by ghcr.io/
    image: flex-development/sneusers
    build:
      args:
        GH_PAT: ${GH_PAT}
        NODE_ENV: ${NODE_ENV}
        NPM_TOKEN: ${NPM_TOKEN}
        PORT: ${PORT}
        WEBPACK_LOG_SECRETS: ${WEBPACK_LOG_SECRETS}
      context: .
      dockerfile: ./Dockerfile
      target: builder
    command: ['yarn', 'run:app', '-wd']
    depends_on:
      - adminer
      - redis
    # NOTE: With the exception of build arguments (see list above) doubling as
    # environment variables, the variables below do NOT need to be exposed.
    # Exposing them enhances DX when inspecting the container in Docker Hub.
    environment:
      CACHE_MAX: ${CACHE_MAX}
      CACHE_TTL: ${CACHE_TTL}
      DB_AUTO_LOAD_MODELS: ${DB_AUTO_LOAD_MODELS}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DEBUG: ${DEBUG}
      DEBUG_COLORS: ${DEBUG_COLORS}
      EMAIL_CLIENT: ${EMAIL_CLIENT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_SEND_AS: ${EMAIL_SEND_AS}
      EMAIL_PRIVATE_KEY: ${EMAIL_PRIVATE_KEY}
      EMAIL_USER: ${EMAIL_USER}
      GH_PAT: ${GH_PAT}
      HOST: ${HOST}
      HOSTNAME: ${HOSTNAME}
      JWT_EXP_ACCESS: ${JWT_EXP_ACCESS}
      JWT_EXP_REFRESH: ${JWT_EXP_REFRESH}
      JWT_EXP_VERIFY: ${JWT_EXP_VERIFY}
      JWT_SECRET_ACCESS: ${JWT_SECRET_ACCESS}
      JWT_SECRET_REFRESH: ${JWT_SECRET_REFRESH}
      JWT_SECRET_VERIFY: ${JWT_SECRET_VERIFY}
      NODE_ENV: ${NODE_ENV}
      NPM_TOKEN: ${NPM_TOKEN}
      PORT: ${PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      THROTTLE_LIMIT: ${THROTTLE_LIMIT}
      THROTTLE_TTL: ${THROTTLE_TTL}
      WEBPACK_LOG_SECRETS: ${WEBPACK_LOG_SECRETS}
      YARN_VERSION: 3.2.0-rc.8
    links:
      - redis:${REDIS_HOST}
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    restart: unless-stopped
    volumes:
      - ./__tests__:/opt/sneusers/__tests__
      - ./.yarn:/opt/sneusers/.yarn
      - ./db/config:/opt/sneusers/db/config
      - ./db/data:/opt/sneusers/db/data
      - ./db/seeds:/opt/sneusers/db/seeds
      - ./db/migrations:/opt/sneusers/db/migrations
      - ./src:/opt/sneusers/src
      - ./tools/helpers:/opt/sneusers/tools/helpers
      - ./typings:/opt/sneusers/typings
      - ./views:/opt/sneusers/views
      - ./.env:/opt/sneusers/.env
      - ./.env.doppler:/opt/sneusers/.env.doppler
      - ./.yarnrc.yml:/opt/sneusers/.yarnrc.yml
      - ./doppler.yaml:/opt/sneusers/doppler.yaml
      - ./nest-cli.json:/opt/sneusers/nest-cli.json
      - ./package.json:/opt/sneusers/package.json
      - ./tsconfig.app.json:/opt/sneusers/tsconfig.app.json
      - ./tsconfig.json:/opt/sneusers/tsconfig.json
      - ./webpack.config.ts:/opt/sneusers/webpack.config.ts
      - ./yarn.lock:/opt/sneusers/yarn.lock
    working_dir: /opt/sneusers
  redis:
    container_name: ${REDIS_HOST}
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    restart: always
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    depends_on:
      - redis
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    restart: always
  server:
    container_name: server
    image: nginx:alpine-perl
    command: ['nginx-debug', '-g', 'daemon off;']
    environment:
      ADMINER_PORT: 8080
      ADMINER_SERVER_NAME: ${ADMINER_SERVER_NAME}
      PORT: ${PORT}
      REDIS_PORT: 8081
      REDIS_SERVER_NAME: ${REDIS_SERVER_NAME}
      SERVER_NAME: ${SERVER_NAME}
    depends_on:
      - adminer
      - app
      - redis-commander
    links:
      - adminer:adminer
      - app:app
      - redis-commander:redis-commander
    ports:
      - 443:443
      - 80:80
    restart: always
    volumes:
      - ./nginx:/etc/nginx:rw
