# DOCKER COMPOSE (DEVELOPMENT)
# https://docs.docker.com/compose/compose-file
# https://github.com/BretFisher/node-docker-good-defaults

name: sneusers

services:
  api:
    container_name: api
    image: ghcr.io/flex-development/sneusers:dev
    build:
      target: code
    command: bun run --watch ./src/main.mts
    environment:
      DOCKER: 1
      HOST: 0.0.0.0
      NEST_DEBUG: 1
      NODE_ENV: development
    hostname: api
    ports:
      - 8080:8080
      - 9229:9229
    pull_policy: build
    restart: always
    tty: true
    volumes:
      - ./package.json:/app/package.json:ro
      - ./src:/app/src:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    working_dir: /app
