# DOCKER COMPOSE (PRODUCTION)
# https://docs.docker.com/compose/compose-file/compose-file-v3
# https://github.com/BretFisher/node-docker-good-defaults

version: '3.9'

services:
  api:
    container_name: api
    image: ghcr.io/flex-development/sneusers:${CONTAINER_IMAGE_TAG:-latest}
    environment:
      APP_ENV: production
      DB_HOSTNAME: $DB_HOSTNAME
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT
      DB_USERNAME: $DB_USERNAME
      HTTPS_CERT: $HTTPS_CERT
      HTTPS_KEY: $HTTPS_KEY
      NEST_DEBUG: 1
      NODE_ENV: production
      NODE_NO_WARNINGS: 1
      URL: $URL
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
    ports:
      - 80:80
      - 443:443
    pull_policy: always
    restart: always
    working_dir: /app
