# DOCKER COMPOSE (DEVELOPMENT)
# https://docs.docker.com/compose/compose-file/compose-file-v3
# https://github.com/BretFisher/node-docker-good-defaults
# https://hub.docker.com/_/mongo
# https://hub.docker.com/_/mongo-express

version: '3.9'

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
services:
  api:
    container_name: api
    image: dev.ghcr.io/flex-development/sneusers
    build:
      args:
        NODE_ENV: development
      context: .
      dockerfile: ./Dockerfile
      secrets:
        - GITHUB_TOKEN
      target: build
    command: nodemon ./src/main.ts
    depends_on: []
    environment:
      APP_ENV: development
      FORCE_COLOR: 3
      HTTPS_CERT: $HTTPS_CERT
      HTTPS_KEY: $HTTPS_KEY
      NODE_ENV: development
      NODE_NO_WARNINGS: 1
      URL: $URL
    healthcheck:
      test: curl --fail http://localhost || exit 1
    ports:
      - 80:80
      - 443:443
    pull_policy: build
    restart: always
    volumes:
      - ./build.config.ts:/app/build.config.ts
      - ./loader.mjs:/app/loader.mjs
      - ./nodemon.json:/app/nodemon.json
      - ./package.json:/app/package.json
      - ./src:/app/src
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./tsconfig.json:/app/tsconfig.json
    working_dir: /app
