version: '3.9'

services:
  app.dev:
    container_name: sneusers
    image: ghcr.io/flex-development/sneusers
    command: yarn run:dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    env_file:
      - ./.env.doppler
    environment:
      DB_AUTO_LOAD_MODELS: ${DB_AUTO_LOAD_MODELS}
      DB_HOST: ${DB_HOST}
      DB_LOGGING: ${DB_LOGGING}
      DB_LOG_QUERY_PARAMS: ${DB_LOG_QUERY_PARAMS}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_TIMEZONE: ${DB_TIMEZONE}
      DB_USERNAME: ${DB_USERNAME}
      DEBUG: ${DEBUG}
      DEBUG_COLORS: ${DEBUG_COLORS}
      DOPPLER_CONFIG: ${DOPPLER_CONFIG}
      DOPPLER_PROJECT: ${DOPPLER_PROJECT}
      DOPPLER_TOKEN: ${DOPPLER_TOKEN}
      GH_PAT: ${GH_PAT}
      HOST:
      HOSTNAME: ${HOSTNAME}
      NODE_ENV: ${NODE_ENV}
      # Causes container to stop running; throws "Unexpected end of JSON input"
      # Unable to leverage DefinePlugin in webpack config
      # NODE_OPTIONS: -r ts-node/register
      NPM_TOKEN: ${NPM_TOKEN}
      PORT: ${PORT}
      SSL_CERT: ${SSL_CERT}
      SSL_KEY: ${SSL_KEY}
      SSL_PASSPHRASE: ${SSL_PASSPHRASE}
    networks:
      - nestjs
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    restart: unless-stopped
    volumes:
      - .:/usr/app:cached
      - node_modules:/usr/app/node_modules:delegated
      - yarn_cache:/usr/app/.yarn/cache:delegated
    working_dir: /usr/app
  app:
    extends:
      service: app.dev
    command: yarn run:prod
    build:
      context: .
      dockerfile: ./Dockerfile
      target: runner

networks:
  nestjs:

volumes:
  node_modules:
  yarn_cache:
