# ISSUE TEMPLATE CHOOSER
# https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

---
blank_issues_enabled: true
contact_links:
  - name: Discuss an idea
    url: https://github.com/flex-development/sneusers/discussions/new?category=ideas
    about: Discuss an idea before submitting a feature request
  - name: Q&A
    url: https://github.com/flex-development/sneusers/discussions/new?category=q-a
    about: Ask and answer questions
