// DATABASE ARCHITECTURE

Project sneusers {
  database_type: 'mysql'
  note: 'demo users system'
}

Table users {
  created_at timestamp [default: `CURRENT_TIMESTAMP`, note: 'when user was created']
  email varchar(254) [unique, note: 'user email address']
  first_name text [note: 'first name of user']
  id int [pk, increment, note: 'user id']
  last_name text [note: 'last name of user']
  updated_at timestamp [note: 'when user was last modified']

  indexes {
    created_at [name: 'created_at']
    email [name: 'email', unique]
    first_name [name: 'first_name']
    id [pk]
    last_name [name: 'last_name']
    updated_at [name: 'updated_at']
  }

  note: 'user info'
}
