// DATABASE ARCHITECTURE

Project sneusers {
  database_type: 'postgresql'
  note: 'demo users system'
}

Table users {
  created_at bigint [not null, default: `EXTRACT(epoch FROM now())`]
  email varchar(254) [unique, not null]
  first_name text [not null]
  id int [pk, increment]
  last_name text [not null]
  updated_at bigint [default: null]

  indexes {
    created_at [name: 'created_at']
    email [name: 'email', unique]
    first_name [name: 'first_name']
    id [pk]
    last_name [name: 'last_name']
    updated_at [name: 'updated_at']
  }

  note: 'user info'
}

Table tokens {
  created_at bigint [not null, default: `EXTRACT(epoch FROM now())`]
  id int [pk, increment]
  revoked boolean [not null, default: false]
  ttl bigint [not null, default: 86400, note: 'time to live']
  type token_type [not null, note: 'jwt type']
  user int [ref: > users.id, not null, note: 'token owner']

  note: 'authentication tokens'
}

enum token_type {
  REFRESH
  VERIFICATION
}
