# Cache Cleanup
#
# Delete all caches created by a branch when a pull request is closed or on workflow dispatch.
#
# References:
#
# - https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
# - https://github.com/actions/checkout
# - https://github.com/actions/gh-actions-cache
# - https://github.com/hmarr/debug-action

---
name: cache-cleanup
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
env:
  BRANCH: |
    ${{ github.event_name == 'workflow_dispatch' && github.ref_name || 'refs/pull/${{
    github.event.pull_request.number }}/merge' }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  cache-cleanup:
    runs-on: ubuntu-latest
    steps:
      - id: debug
        name: Print environment variables and event payload
        uses: hmarr/debug-action@v2.1.0
      - id: checkout
        name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3.5.0
        with:
          ref: ${{ github.ref_name }}
      - id: gh-actions-cache
        name: Install actions/gh-actions-cache
        run: gh extension install actions/gh-actions-cache
      - id: cleanup
        name: Delete caches created by ${{ env.BRANCH }}
        run: |
          # prevent workflow failure while deleting cache keys
          set +e

          # delete caches created by $BRANCH
          for key in $(gh actions-cache list -B $BRANCH -R ${{ github.repository }} | cut -f 1); do
            gh actions-cache delete $key -B $BRANCH -R ${{ github.repository }} --confirm
          done
