# Continuous Integration - dbdocs
#
# References:
#
# - https://github.com/actions/checkout
# - https://github.com/actions/setup-node
# - https://dbdocs.io/docs/ci-integration

---
name: ci-dbdocs
on:
  pull_request:
    paths:
      - docs/DATABASE.dbml
  push:
    branches:
      - next
    paths:
      - docs/DATABASE.dbml
  workflow_dispatch:
jobs:
  ci-dbdocs:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - id: install-dbdocs
        name: Install dbdocs
        run: sudo npm install -g dbdocs
      - id: build-dbdocs
        name: Build dbdocs project
        run: dbdocs build ./docs/DATABASE.dbml
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
