# Continuous Integration
#
# References:
#
# - https://github.com/actions/checkout
# - https://github.com/actions/setup-node
# - https://github.com/DopplerHQ/cli-action

---
name: continuous-integration
on:
  pull_request:
  push:
    branches:
      - next
      - push-action/**
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.PAT_GPR_ADMIN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_ADMIN }}
    strategy:
      matrix:
        node: [14.13.1]
    steps:
      - id: checkout
        name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - id: node
        name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          scope: '@${{ github.repository_owner }}'
      - id: install-deps
        name: Install dependencies
        run: yarn --immutable
        env:
          NODE_AUTH_TOKEN: ${GH_PAT}
      - id: doppler-cli
        name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1
      - id: check-format
        name: Check code formatting
        run: yarn check:format
      - id: check-style
        name: Check code style
        run: yarn check:style
      - id: test
        name: Run test suites
        run: yarn test
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_TEST }}
      - id: build
        name: Build project
        run: doppler run --command="NODE_ENV=test yarn build:app"
        env:
          DOPPLER_CONFIG: ${{ secrets.DOPPLER_CONFIG }}
          DOPPLER_ENVIRONMENT: ${{ secrets.DOPPLER_ENVIRONMENT }}
          DOPPLER_PROJECT: ${{ secrets.DOPPLER_PROJECT }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
