# Virtual Machine Docker Compose
#
# Upload Docker Compose file for virtual machine to project storage bucket when the Docker Compose
# or startup script files are modified, or on workflow dispatch.
#
# References:
#
# - https://cloud.google.com/sdk/gcloud/reference/storage/cp
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#push
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
# - https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#push
# - https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch
# - https://github.com/actions/checkout
# - https://github.com/google-github-actions/auth
# - https://github.com/google-github-actions/setup-gcloud
# - https://github.com/hmarr/debug-action

---
name: vm-compose
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/vm-compose.yml
      - docker-cloud.yml
      - scripts/vm/startup-script.sh
  workflow_dispatch:
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  vm-compose:
    if: startsWith(github.event.head_commit.message, 'release:') == false
    runs-on: ubuntu-latest
    steps:
      - id: debug
        name: Print environment variables and event payload
        uses: hmarr/debug-action@v2.1.0
      - id: checkout
        name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3.4.0
        with:
          ref: ${{ github.ref_name }}
      - id: gcloud-auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.GCE_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
      - id: gcloud-setup
        name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.0
        with:
          project_id: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
          skip_install: true
      - id: upload
        name: Upload Docker Compose file to storage bucket
        run: gcloud storage cp ./docker-cloud.yml gs://$CLOUDSDK_CORE_PROJECT/app/docker-compose.yml
